/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package security2.kt6

import org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
import org.bouncycastle.util.Strings
import org.bouncycastle.util.encoders.Hex
import java.math.BigInteger
import java.security.SecureRandom
import java.security.Security
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {

    @BeforeTest fun start() {
        Security.addProvider(BouncyCastleFipsProvider())
    }

}
